### ISSUE TITLE
Sort D3 entities by overlaps

### ISSUE THREAD

**Issue by chrismattmann** [manalishah/Tika-NLTKvsCoreNLP#2]
Hey @manalishah can you sort the D3 entities in order from:
1. Maximum overlap (most overlapping entities between NLTK and CoreNLP/NER)

Also can you clean up the viz a bit (the 0 shows kind of odd). Thanks!

**Comment by manalishah** [comment]
Hey @chrismattmann, D3 entries in the form of most overlap is done. It definitely makes more sense that way.

I am working on cleaning the D3

**Comment by manalishah** [comment]
@chrismattmann D3 is fixed and visualizes 500 urls from imagecatdev belonging to gunsamerica.
